### ISSUE TITLE
How to redirect to particular view(customView) after facebook login authentication

### ISSUE THREAD

**Issue by narasimhanallamsetty** [Hipo/HPSocialNetworkManager#11]
After login authentication user has to be redirected to particular screen(not rootViewController). How can it be done can anyone tell me..

After authentication controller reaches to rootviewController. But I need to display different view after successful login. Every one prepares tutorials  incompletely I don't know why? can anyone help me...

**Comment by taylanpince** [comment]
You can just use the completion block and do anything you want inside it. This is clearly outlined in the example code.
